# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80468177d3fe78c6dcbd9d4f187c44be4a37a277ea7e928b32f4902d6e0f05a7364008c3e6694e3683585127794f479599f1f110c9430f1ff2a390b39b91174d

test:
  secret_key_base: 444cf58d0928391ea601715e007c337514697a2764f23e45c082e38fb266cf96534d00f4ef75daf8864c4d868ca0fe153096561630179566757976a8b32534a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
